#!/bin/bash
name=$(
	yad --entry \
	--center \
	--text="Enter A Name For Your Reminder" \
	--title="Reminder Name" \
	--width=450 \
	2>/dev/null
)

time=$(yad --entry \
--center \
--text="Hola Boss, When Do You Want To Be Reminded" \
--title="Reminder" \
--width=300 \
2>/dev/null
)
cases=("tomorrow" "next week" "hour" "minute" "minutes" "days" "today" "min" "mins" "hr")
dow=("monday" "tuesday" "wednesday" "thursday" "friday" "saturday" "sunday")
special_cases=("september" "april" "june" "november")
months=("january" "february" "march" "april" "may" "june" "july" "august" "september" "october" "november" "december")
decideWhen(){
date=$(tr '[:upper:]' '[:lower:]' <<< "$@")
time=$(sed 's@[a-z]@@g' <<< $date | sed 's/ //g')
for i in "${cases[@]}"; do
	if [[ "$date" =~ "$i" ]] || [[ $date =~ [[:digit:]] ]]; then
		case $date in
		*"today"*)
				declare -i secs_to_sleep=0
				hr=0; minit=0
				custom_time=$(sed 's@[a-z,A-Z]@@g' <<< $date)
				if [ ! -z $(grep -i -o pm <<< $date) ]; then
					TOD=pm
				elif [[ ! -z $(grep -i -o am <<< $date) ]]; then
					TOD=am
				else
					TOD=$(zenity --entry --text="$custom_time AM or PM" --title="AM or PM" --width=200 2>/dev/null)
					TOD=$(tr '[:upper:]' '[:lower:]' <<< $TOD)
				fi
				hour=00 ; min=00 ; sec=00
					declare -i counter=0
					IFS=':'; for i in $time ; do
					if [ $counter -eq 0 ]; then
						hr=$i					
						hour=$(printf '%02g' $i)
						counter+=1
					elif [ $counter -eq 1 ]; then
						minit=$i
						min=$(printf '%02g' $i)
						counter+=1					
					fi
				done
				time="$hour":"$min"
				#echo "Got it, I'll Remind You At $time $TOD"
				if [ "$TOD" == "pm" ]; then
					hour=$((hour+12))
				fi
				if [ "$TOD" == "pm" ] && [ $hr -lt 12 ]; then
					hr=$((hr+12))
				fi

				if [ "$TOD" == "am" ] && [ $hr -eq 12 ]; then
					hr=0
				fi
				
				heur=$(date +%H)
				min=$(date +%M)
				if [ "$TOD" == "am" ] && [ $hr -lt $(date +%H) -a ! $hr -eq 0 ]; then
				hr=$((hr+24))
			fi
				heur=$((hr-heur))
				min_diff=$((minit-min))
				if [ $minit -lt $(date +%M) ] && [ $hr -gt $(date +%H) ]; then
					min_diff=$((60+minit))
					minit=$(date +%M)
					min_diff=$((min_diff-minit))
					heur=$((heur-1))
				fi
				secs_to_sleep=$((heur*3600))
				secs_to_sleep+=$((min_diff*60))
				if [ $heur -gt 0 ]; then
					yad --center --image=dialog-information --text="Reminder "$name" Set For $heur hours $min_diff minutes From Now" --width=300 --title="Reminder Set" --button=gtk-ok 2>/dev/null &
				else
					yad --center --image=dialog-information --text="Reminder "$name" Set For $min_diff minutes From Now" --width=300 --title="Reminder Set" --button=gtk-ok 2>/dev/null &
				fi				
					#IFS=','
					#local params=("today" "$secs_to_sleep")			
					#echo "${params[@]}"
					echo $secs_to_sleep
				
				break
				;;
		*"tomorrow"*)hr=0; minit=0
				custom_time=$(sed 's@[a-z,A-Z]@@g' <<< $date)
				if [ -z $custom_time ]; then
					time=$(zenity --entry --text="What Time Do You Want To Be Reminded Tomorrow? \n Leave Blank To Use Present Time" --width=300 --title="Time?" 2>/dev/null)
					[ ! -z $time ]||{
						time="$(date +%I):$(date +%M)$(date +%P)"
					}
				fi				
				if [ ! -z $time ]; then
				if [ ! -z $(grep -i -o pm <<< $time) ]; then
					TOD=pm
				elif [[ ! -z $(grep -i -o am <<< $time) ]]; then
					TOD=am
				else
					TOD=$(zenity --entry --text="$time AM or PM" --title="AM or PM" --width=200 2>/dev/null)
					TOD=$(tr '[:upper:]' '[:lower:]' <<< $TOD)				
			fi
		fi
				time=$(sed 's@[a-z]@@g' <<< $time | sed 's/ //g')
				day=$(date +%A)
				day=$(tr '[:upper:]' '[:lower:]' <<< $day)
			     declare -i date=$(date +%d)
			    date+=1
			for dey in ${!dow[@]}; do
				[ "${dow[$dey]}" != "$day" ]||{
				[ $((dey+1)) != ${#dow[@]} ]||{
					dey=-1
				}
					day="${dow[$((dey+1))]}"
					day=$(echo -n ${day^} "")
					break			
				}
			done			
			mnth=$(tr '[:upper:]' '[:lower:]' <<< $(date +%B))
			for months in ${special_cases[@]};do
				if [ "$months" == "$munth" ]; then
					overflow=1
				fi
			done
			if [ $date -gt 30 ]; then				
				if [ ! -z $overflow ]; then
					for mth in ${!months[@]}; do
					if [ "$mnth" == "${months[$mth]}" ]; then
						mnth=${months[$((mth+1))]}
						break
					fi
				done
					date=$((date-30))
				fi
			fi
			if [ $date -gt 31 ]; then
				for mth in ${!months[@]}; do
					if [ "$mnth" == "${months[$mth]}" ]; then
						mnth=${months[$((mth+1))]}
						break
					fi
				done
				date=$((date-31))
			fi
			mnth=$(echo -n ${mnth^} "")
			if [ -z $time ]; then
				time=$(date +%R)
			else
				hour=00 ; min=00 ; sec=00
					declare -i counter=0
					IFS=':'; for i in $time ; do
					if [ $counter -eq 0 ]; then
					hr=$i						
						hour=$(printf '%02g' $i)
						counter+=1
					elif [ $counter -eq 1 ]; then
						minit=$i
						min=$(printf '%02g' $i)
						counter+=1					
					fi
				done
				time="$hour":"$min"
			fi			
			declare -i secs_to_sleep=0
			declare -i secs_to_tomorrow=0
			if [ "$TOD" == "pm" ] && [ $hr -lt 12 ]; then
					hr=$((hr+12))
			fi
			if [ "$TOD" == "am" ] && [ $hr -eq 12 ]; then
				hr=0
			fi
				
			heur=$(date +%H)
			min=$(date +%M)
			if [ "$TOD" == "am" ] && [ $hr -lt $(date +%H) -a ! $hr -eq 0 ]; then
				hr=$((hr+24))
			fi
			heur=$((24-heur))	
			if [ $minit -lt $(date +%M) ]; then
				tom_minit=$(date +%M)
				min_diff=$((60-tom_minit))
				heur=$((heur-1))
			fi
			hr=$hr
			secs_to_tomorrow=$((heur*3600))
			secs_to_tomorrow+=$((min_diff*60))
			secs_to_sleep+=$secs_to_tomorrow
			secs_to_sleep+=$((hr*3600))
			secs_to_sleep+=$((minit*60))
			yad --center --image=dialog-information --text="Reminder Set For $day $date, $mnth At $time $TOD" --title="Reminder" --button=gtk-ok --width=450 2>/dev/null &
			#local params=("today" "$secs_to_sleep")
			#echo "${params[@]}"
			echo $secs_to_sleep
			break
			;;
		*"hour"*|*"min"*|*"hr"*) declare -i secs_to_sleep=0
						 custom_time=$(sed 's@[a-z,A-Z]@@g' <<< $date)						
						if [ ! -z "$(grep -i min <<< $date)" ] && [ ! -z "$(grep -i hour <<< $date)" ]; then
						declare -i counter=0
						IFS=' ';for i in $custom_time ; do							
							if [ $counter -eq 0 ]; then	
								secs_to_sleep=$((i*3600))														
								hour=$(printf '%02g' $i)								
								hour=$(($(date +%H)+hour))								
								counter+=1
								continue
							fi
								secs_to_sleep+=$((i*60))		
								minute=$(printf '%02g' $i)
								minit=$(date +%M)					
								minute=$((minute+minit))

						done
					fi
					if [ -z "$(grep -i min <<< $date)" ] && [ ! -z "$(grep -i hour <<< $date)" ]; then
					hour=$time
					secs_to_sleep=$((hour*3600))
					minute=$(date +%M)
					hour=$(($(date +%H)+hour))
				elif [ ! -z "$(grep -i min <<< $date)" ] && [ -z "$(grep -i hour <<< $date)" ]; then
					minute=$time
					secs_to_sleep=$((minute*60))
					hour=$(date +%H)
					date_minute=$(date +%M)
					minute=$((date_minute+minute))
				fi
					if [ $hour -gt 24 -o $hour -eq 24 ]; then
						hour=$(printf '%02g' $((hour-24)))						
					fi	
					if [ $minute -gt 60 -o $minute -eq 60 ]; then
						minute=$(printf '%02g' $((minute-60)))
						hour=$(printf '%02g' $((hour+1)))
					fi
					
					if [ $hour -gt 12 ]; then
						display_hour=$((hour-12))
						TOD=Pm
					else
						display_hour=$hour
						TOD=Am
					fi
					yad --image=dialog-information --center --text="Reminder $name Set For $display_hour:$minute $TOD" --width=300 --title="Reminder Set" 2>/dev/null &
					#IFS=','
					#local params=("today" "$secs_to_sleep")					
					#echo "${params[@]}"
					echo $secs_to_sleep
					break
					;;

		*"days"*|*"day"*) day=$(date +%A)
					mnth=$(tr '[:upper:]' '[:lower:]' <<< $(date +%B))
				  day=$(tr '[:upper:]' '[:lower:]' <<< $day)
				  custom_date=$(sed 's@[a-z,A-Z]@@g' <<< $date)
				  IFS=' '; for i in $custom_date; do
				  	time=$i
				  	break
				  done
				  declare -i date=$(date +%d)				  
				  date+=$time
				  for dey in ${!dow[@]}; do
				[ "${dow[$dey]}" != "$day" ]||{
				[ $((dey+1)) != ${#dow[@]} ]||{
					dey=-1
				}
					dey=$((dey+time))					
					dey=$((dey%${#dow[@]}))
					#dey=$((dey-1))
					day="${dow[dey]}"
					day=$(echo -n ${day^} "")
					break			
				}
			done	
			
			for months in ${special_cases[@]};do
				if [ "$months" == "$mnth" ]; then
					overflow=1
				fi
			done
			if [ $date -gt 30 ]; then				
				if [ ! -z $overflow ]; then
					for mth in ${!months[@]}; do
					if [ "$mnth" == "${months[$mth]}" ]; then
						mnth=${months[$((mth+1))]}
						break
					fi
				done
					date=$((date-30))
				fi
			fi
			if [ $date -gt 31 ]; then
				for mth in ${!months[@]}; do
					if [ "$mnth" == "${months[$mth]}" ]; then
						mnth=${months[$((mth+1))]}
						break
					fi
				done
				date=$((date-31))
			fi
			time=$(sed 's@[[:digit:]]@@' <<< $custom_date | sed 's/ //g')
			if [ -z $time ]; then
				time=$(date +%R)
			else
				hour=00 ; min=00 ; sec=00
					declare -i counter=0
					IFS=':'; for i in $time ; do
					if [ $counter -eq 0 ]; then
						hour=$(printf '%02g' $i)
						counter+=1
					elif [ $counter -eq 1 ]; then
						min=$(printf '%02g' $i)
						counter+=1					
					fi
				done
				time="$hour":"$min"
			fi
			mnth=$(echo -n ${mnth^} "")
			declare -A details			
			echo "Sure, I'll Remind You On $day $date, $mnth at $time"
			break
					;;

		*"next week"*|*"next-week"*)
					echo "Work In Progress, Coming Soon"
					;;
		*[[:digit:]]*)
					declare -i secs_to_sleep=0					
					custom_time=$(sed 's@[a-z,A-Z]@@g' <<< $date)
					if [ ! -z $(grep -i -o pm <<< $date) ]; then
					TOD=pm
				elif [[ ! -z $(grep -i -o am <<< $date) ]]; then
					TOD=am
				else
					TOD=$(zenity --entry --text="$custom_time AM or PM" --title="AM or PM" --width=200 2>/dev/null)
					TOD=$(tr '[:upper:]' '[:lower:]' <<< $TOD)
				fi
					declare -i counter=0
					hour=00 ; min=00 ; sec=00
					IFS=':'; for i in $time ; do
					if [ $counter -eq 0 ]; then
						hr=$i						
						hour=$(printf '%02g' $i)
						counter+=1
					elif [ $counter -eq 1 ]; then
						minit=$i
						min=$(printf '%02g' $i)
						counter+=1					
					fi
					
				done
				tm="$hour":"$min"				
				if [ "$TOD" == "pm" ] && [ $hr -lt 12 ]; then
					hr=$((hr+12))
				fi

				if [ "$TOD" == "am" ] && [ $hr -eq 12 ]; then
					hr=0
				fi
				
				heur=$(date +%H)
				min=$(date +%M)
				if [ "$TOD" == "am" ] && [ $hr -lt $(date +%H) -a ! $hr -eq 0 ]; then
				hr=$((hr+24))
			fi
				heur=$((hr-heur))
				min_diff=$((minit-min))
				if [ $minit -lt $(date +%M) ] && [ $hr -gt $(date +%H) ]; then
					min_diff=$((60+minit))
					minit=$(date +%M)
					min_diff=$((min_diff-minit))
					heur=$((heur-1))
				fi
				secs_to_sleep=$((heur*3600))
				secs_to_sleep+=$((min_diff*60))
				if [ $heur -gt 0 ]; then
					yad --center --image=dialog-information --text="Reminder "$name" Set For $heur hours $min_diff minutes From Now" --width=300 --title="Reminder Set" --button=gtk-ok 2>/dev/null &
				else
					yad --center --image=dialog-information --text="Reminder "$name" Set For $min_diff minutes From Now" --width=300 --title="Reminder Set" --button=gtk-ok 2>/dev/null &
				fi				
					#IFS=','
					#local params=("today" "$secs_to_sleep")			
					#echo "${params[@]}"
					echo $secs_to_sleep
				break
					;;		
		*) echo "No case For This Yet";;
		esac
	fi
done
}
#formerIFS="$IFS"
#IFS=','
#x=($(decideWhen $time))
#IFS="$formerIFS"
#declare -i counter=0
#for i in ${x[@]}; do
#	if [ $counter -eq 0 ]; then
#		when=$i
#		counter+=1
#	elif [ $counter -eq 1 ]; then
		interval=$(decideWhen $time)
#		counter+=1	
#	fi
#done

#case $when in 
#	"today") 
			sleep $interval
			zenity --info --text="Yo, Here's The Reminder For: $name" --title="Reminder" --width=300 2>/dev/null
			exit 0
#			;;
#	*) echo "Something Is Really Wrong, Code Is Not Supposed To Reach Here"
#		;;
#	esac